### ISSUE TITLE
unagi-chan in Stackage?

### ISSUE THREAD

**Issue by bhipple** [jberryman/unagi-chan#16]
It would be great to have this library supported in the Stackage LTS.  Do you have the bandwidth to add it to the distribution, by any chance?

https://github.com/fpco/stackage/#add-your-package

**Comment by jberryman** [comment]
Thanks for the prod, and for linking to instructions. I use stackage myself, and will try to do that as soon as I can.

**Comment by jberryman** [comment]
Hey it would be great if someone wanted to volunteer to be the stackage maintainer, and take on the responsibilities there (dealing with breakage and fiddling with version bounds or whatever needs to be done). Not sure what that person would need from me, but I don't super have an interest in taking that on personally, it turns out.
