### ISSUE TITLE
Test time out on Stackage

### ISSUE THREAD

**Issue by decentral1se** [jberryman/unagi-chan#21]
```
unagi-chan: BuildFailureException Test suite timed out: unagi-chan-0.4.0.0:test
```

I've added the package to the `expected-test-failures` for time outs. Hopefully this ticket can track any changes you can make that can get this fixed up.

**Comment by jberryman** [comment]
Thanks, what is their build server using for a timeout value?

**Comment by shmish111** [comment]
Hey, is there any chance of unagi getting on stackage? maybe something I can do to help?

**Comment by lwm** [comment]
I'm not maintaining at Stackage any more but I would raise an issue on the stackage issue tracker if you have any question. They are always happy to help. BTW, @shmish111, this issue is just about disabling the test suite for stackage. If this package is blocked, that is for another reason - hope it helps!
