### ISSUE TITLE
Document tryReadChan/Element better w/r/t destructive nature of operation

### ISSUE THREAD

**Issue by jm4games** [jberryman/unagi-chan#30]
So I am trying to track down an issue I am seeing when using channels with parallel threads. Here is the current scenario that I am seeing give me problems.

Channel: Control.Concurrent.Chan.Unagi

Setup:
I have two threads A and B that share a channel Q; A is producer and B is consumer. Thread A consumes a stream of data and notifies Thread B when the stream is consumed (due to an exception or graceful finish) via a message to the Q.  Thread A will then wait for thread B to fully exit by blocking on a takeMVar that is set by a putMvar in thread B.

Scenario:
Thread A and thread B are both created using forkIO and thread B blocks on Q with a "readChan" waiting for messages. Thread A begins processing a stream of data. Eventually  thread A has an exception reading stream, catches it and sends a message to B (via Q) to exit. Thread A blocks on MVar, concurrently Thread B receives the exit message and sets the MVar, then exits. Thread A takeMVar succeeds and then clears the Q of any possible messages remaining in it.  Thread A then proceeds to retry reading the stream, upon success a new thread B (view forkIO) is created and again thread B blocks on a readChan (on original Q). Eventually another exception is thrown on thread A while reading the stream, so again thread A sends the exit message to B (via Q) and then blocks on MVar waiting on thread B to exit.  Only this time thread B never seems to receive the message and sits waiting to read a message from the  Q. 

-----------------
So I should call out this doesn't happen every time, sometimes I can get through the work/fail/spawn loop a couple of times before it fails. This leads me to believe it is probably some sort of rare race condition. I'm assuming I don't need to use the readChanOnException within Thread B since this is not where the exception is being generated. I might try using the non-blocking channel with streams and see if it makes a difference. But any thoughts on this would be great!

**Comment by jberryman** [comment]
Would you mind posting an example? Ideally it could reproduce the issue, but even if it just illustrates the scenario you've described above that would be helpful. Thanks!

**Comment by jm4games** [comment]
Sure give me a few.

**Comment by jm4games** [comment]
So here is a minimal example. The example actually does reproduce my scenario, but it exits on second loop due to mvar dead lock issue, which makes me think maybe my application is seeing same issue. My logic looks sound, but maybe I am missing something?

Cabal:
name:                chan-demo
version:             0.2.1.0
build-type:          Simple
cabal-version:       >= 1.10

executable chan-demo
  default-language: Haskell2010
  ghc-options:      -Wall -fwarn-tabs -funbox-strict-fields -threaded -fno-warn-unused-do-bind -O2
  ghc-prof-options: -fprof-auto
  main-is: src/Main.hs

  build-depends:
    base                    >= 4.9 && < 4.11,
    random                  >= 1.1 && < 1.2,
    unagi-chan              >= 0.4 && < 0.5

Main.hs
{-# LANGUAGE ScopedTypeVariables #-}

module Main where

import Control.Monad (forever)
import Control.Concurrent (forkIO)
import Control.Concurrent.MVar
import Control.Exception (SomeException, catch)

import System.Random (randomIO)

import qualified Control.Concurrent.Chan.Unagi as Unagi


data Cmd = Loop | Exit deriving Show

main:: IO ()
main = do
  (inChan, outChan) <- Unagi.newChan
  mvar <- newEmptyMVar
  forever $ do
    putStrLn "New Loop"
    _ <- forkIO $ threadB mvar outChan `catch` (\(e :: SomeException) ->
      putStrLn "Thread B exited with exception" >> print e)
    threadA mvar inChan outChan

threadA :: MVar () -> Unagi.InChan Cmd -> Unagi.OutChan Cmd -> IO ()
threadA mvar inChan outChan = do
  loop `catch` (\(_ :: SomeException) ->
    putStrLn "caught ex, send exit" >> Unagi.writeChan inChan Exit >> putStrLn "exit sent")
  putStrLn "take mvar"
  takeMVar mvar
  putStrLn "mvar taken"
  clearOutChan -- just in case (for demo, nothing should be left in chan)
  where
    loop = do
      r <- randomIO :: IO Int
      if r `mod` 2 == 0 then loop else error "Failure!!"
    clearOutChan =
      Unagi.tryReadChan outChan >>= Unagi.tryRead . fst >>= maybe (return ()) (const clearOutChan)

threadB :: MVar () -> Unagi.OutChan Cmd -> IO ()
threadB mvar inChan = do
  putStrLn "try read cmd"
  msg <- Unagi.readChan inChan
  putStrLn ("cmd read: " ++ show msg)
  case msg of
    Exit -> putStrLn "put mvar" >> putMVar mvar () >> putStrLn "mvar put complete"
    Loop -> threadB mvar inChan -- Nvr actually used in example

**Comment by jm4games** [comment]
So interestingly enough, if I recreate the channel every loop. Everything works fine.

**Comment by jm4games** [comment]
So I looked into this a bit more, it seems the readMVar in Control.concurrent.chan.Unagi.Internal line 195 is where this blows up. I'm wondering if GHC does not recognize that fact that the mvar atomically written to the array is accessible by other threads. I have no idea how the deadlock detection in GHC works.

**Comment by jm4games** [comment]
So if we remove the clearOutChan after the take, the sample program works. Why taking that out fixes it is beyond me since the MVar exception is thrown before we even enter that code.

**Comment by jberryman** [comment]
Thanks for the helpful info and sorry for the delay, I've been traveling. I'll look into this in the next few days.

**Comment by jberryman** [comment]
So the first thing I see is that `tryReadChan` doesn't quite work the way you think. Calling `tryReadChan` acts like a read of _an element that might not yet have been written to the queue_. i.e. `tryReadChan` is destructive; if you find that `tryRead` returns `Nothing` and then you discard the `Element` and proceed to do other stuff it means that exactly one item written to the queue (possibly in the future) is (will be) lost.

So I think what you're seeing is your `readChan` waiting for an element (internally blocking on an MVar) that will never arrive (it's the element from the `Element` returned in `clearOutChan` that you needed). `threadB` dies then the main thread is killed since it's blocked on `mvar` and holds the only reference.

Re-reading the documentation I can see I tried but probably failed to make this sort of tricky behavior clear. I'll mark this as a documentation bug if that seems to be the issue you were seeing, but let me know if that doesn't seem to have been the whole issue.

Random notes on deadlock detection, AFAIU: GHC will raise the special `BlockedIndefinitelyOnMVar` exception if the thread is blocked and there are no other references to that `MVar` from threads that are not themselves blocked on that var. There may be more complex rules in the runtime, but the main things I think to remember are:
- the runtime cannot detect all logical deadlocks
- the exception is not recoverable, i.e. you can catch it and sometimes e.g. print a message but the thread will still be GC'd

**Comment by jm4games** [comment]
Ok thanks. I fairly certain the behavior you described is what I am seeing. I switched over to using the non-blocking channels mimicking the usage pattern from before and do not see the same problem. If the tryRead is destructive, that would explain why.
